name: Feature Request
description: Suggest a new feature
title: "feature: "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Did you check the docs?
      options:
        - label: I have read all of the plugin's docs
          required: true
  - type: checkboxes
    attributes:
      label: Are there no similiar feature requests?
      options:
        - label: There are no existing requests for this feature
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature and solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
